Frontend/HotelProject.WebUI/Controllers/BookingAdminController.cs
using HotelProject.WebUI.Dtos.BookingDto;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace HotelProject.WebUI.Controllers
{
    public class BookingAdminController : Controller
    {
        //API'ın Consume Edilmesi
        private readonly IHttpClientFactory _httpClientFactory;

        public BookingAdminController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient(); //İstemci oluşturduk.
            var responseMessage = await client.GetAsync("http://localhost:50430/api/Booking"); //Adrese istekte bulunduk.
            if (responseMessage.IsSuccessStatusCode) //Başarılı durum kodu dönerse
            {
                var jsondata = await responseMessage.Content.ReadAsStringAsync(); //Gelen veri jsondata değişkenine aktarıldı. jsondata json türünde.
                var values = JsonConvert.DeserializeObject<List<ResultBookingDto>>(jsondata); //Tablomuza verinin aktarılması için deserialize işlemi yapıldı.
                return View(values);
            }
            return View();
        }

        public async Task<IActionResult> ApprovedReservation(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("http://localhost:50430/api/Booking/BookingAproved?id=" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> CancelReservation(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"http://localhost:50430/api/Booking/BookingCancel?id={id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> WaitReservation(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"http://localhost:50430/api/Booking/BookingWait?id={id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> UpdateBooking(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"http://localhost:50430/api/Booking/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<UpdateBookingDto>(jsonData);
                return View(values);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBooking(UpdateBookingDto updateBookingDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(updateBookingDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync("http://localhost:50430/api/Booking/", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Frontend/HotelProject.WebUI/Views/BookingAdmin/Index.cshtml
@model List<ResultBookingDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
    int count = 0;
}

<h2>Rezervasyonlar</h2>
<br />
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Misafir</th>
                <th>Giriş Tarihi</th>
                <th>Çıkış Tarihi</th>
                <th>Durum</th>
                <th>İşlem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                count++;
                <tr>
                    <th>@count</th>
                    <td>@item.Name</td>
                    <td>@(((DateTime)item.CheckIn).ToString("dd MMM yyyy"))</td>
                    <td>@(((DateTime)item.CheckOut).ToString("dd MMM yyyy"))</td>
                    <td><span class="badge badge-primary px-2">@item.Status</span></td>

                    <td>
                        <div class="dropdown">
                            <button class="btn btn-sm btn-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <small>Seçiniz</small>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="btn btn-success dropdown-item" href="/BookingAdmin/ApprovedReservation/@item.BookingID/">Onayla</a>
                                <a class="btn btn-danger dropdown-item" href="/BookingAdmin/CancelReservation/@item.BookingID/" onclick="return confirm('Bu rezervasyonu iptal etmek isteğinize emin misiniz?')">İptal Et</a>
                                <a class="btn btn-warning dropdown-item" href="/BookingAdmin/WaitReservation/@item.BookingID/">Beklet</a>
                                <a class="btn btn-primary dropdown-item" href="/BookingAdmin/UpdateBooking/@item.BookingID/">Güncelle</a>
                                <a class="btn btn-dark dropdown-item" href="/BookingAdmin/UpdateBooking/@item.BookingID/">Detaylar</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Frontend/HotelProject.WebUI/Views/BookingAdmin/UpdateBooking.cshtml
@model UpdateBookingDto
@{
    ViewData["Title"] = "UpdateBooking";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
}
<h2>Rezervasyon Güncelleme Sayfası</h2>

<form method="post" asp-action="UpdateBooking" asp-controller="BookingAdmin">
    <input type="hidden" asp-for="BookingID"/>
    <label>Misafir Adı Soyadı</label>
    <input type="text" asp-for="Name" class="form-control" />
    <br />
    <label>Misafir Mail Adresi</label>
    <input type="text" asp-for="Mail" class="form-control" />
    <br />
    <label>Misafir Giriş Tarihi</label>
    <input type="date" asp-for="Checkin" class="form-control" />
    <br />
    <label>Misafir Çıkış Tarihi</label>
    <input type="date" asp-for="CheckOut" class="form-control" />
    <br />
    <label>Yetişkin Sayısı</label>
    <input type="text" asp-for="AdultCount" class="form-control" />
    <br />
    <label>Çocuk Sayısı</label>
    <input type="text" asp-for="ChildCount" class="form-control" />
    <br />
    <label>Oda Sayısı</label>
    <input type="text" asp-for="RoomCount" class="form-control" />
    <br />
    <label>Şehir</label>
    <input type="text" asp-for="City" class="form-control" />
    <br />
    <label>Ülke</label>
    <input type="text" asp-for="Country" class="form-control" />
    <br />
    <label>Durum</label>
    <input type="text" asp-for="Status" class="form-control" />
    <br />
    <label>Özel İstekler</label>
    <textarea asp-for="SpecialRequest" rows="4" class="form-control"></textarea>
    <br />
    <label>Açıklama</label>
    <textarea asp-for="Description" rows="4" class="form-control"></textarea>
    <br />
    <button class="btn btn-rounded btn-success">Verileri Kaydet</button>
</form>